a = float(input("Введите первое число: "))
b = float(input("Введите второе число: "))
c = float(input("Введите третье число: "))
max_number = max(a, b, c)
print(f"Наибольшее число: {max_number}")
min_number = min(a, b, c)
print(f"Наименьшее число: {min_number}")
are_equal = (a == b == c)
print(f"Все числа равны: {are_equal}")